name: Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  PYTHON_VERSION: 3.x

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Setup Tex Live
        run: |-
          sudo apt update
          sudo apt install texlive-full
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
      - name: Install Python Dependencies
        run: pip install --requirement=requirements.txt
      - name: Deploy to GitHub Pages
        run: make docs-gh-deploy
